Pin mutant to working version 0.7.4
It seems that mutant 0.7.5 is broken for me.

Running `rake mutant ROM::Repositry` fails with:

    Mutant configuration:
    Matcher:         #<Mutant::Matcher::Config match_expressions=[<Mutant::Expression: ROM::Repository>] subject_ignores=[<Mutant::Expression: ROM::Repository#respond_to_missing?>] subject_selects=[]>
    Integration:     rspec
    Expect Coverage: 100.00%
    Jobs:            2
    Includes:        ["lib"]
    Requires:        ["rom"]
    Subjects:        10
    Mutations:       286
    Kills:           0
    Alive:           0
    Runtime:         0.18s
    Killtime:        0.00s
    Overhead:        Inf%
    Coverage:        0.00%
    Expected:        100.00%
    Active subjects: 0
    Active Jobs:
    0: neutral:ROM::Repository.class_from_symbol:/home/peter/devel/rom/lib/rom/repository.rb:35:bf9a2
    1: evil:ROM::Repository.class_from_symbol:/home/peter/devel/rom/lib/rom/repository.rb:35:aa926
    /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:456:in `print_tests': undefined method `each' for nil:NilClass (NoMethodError)
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:422:in `run'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:22:in `run'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:70:in `visit'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:56:in `block in visit_collection'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:55:in `each'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:55:in `visit_collection'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:151:in `run'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:22:in `run'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/format.rb:72:in `format'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli/format.rb:147:in `progress'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/reporter/cli.rb:47:in `progress'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/runner.rb:57:in `block in run_driver'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/runner.rb:55:in `loop'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/runner.rb:55:in `run_driver'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/runner.rb:39:in `run_mutation_analysis'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/runner.rb:17:in `initialize'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/procto-0.0.2/lib/procto.rb:62:in `block in initialize'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/lib/mutant/cli.rb:25:in `run'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/gems/mutant-0.7.5/bin/mutant:19:in `<top (required)>'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/bin/mutant:23:in `load'
            from /home/peter/.rvm/gems/ruby-2.1.5@pg/bin/mutant:23:in `<main>'