Prefer `registered` method over ivar in Repository
This fixes a possible bug which cannot be spec'ed yet:

    require 'rom'

    p ROM::Repository[:foo]

fails with

/rom/lib/rom/repository.rb:75:in `[]': undefined method `detect' for nil:NilClass (NoMethodError)
  from foo.rb:4:in `<main>'